### ISSUE TITLE
Wrapping Elixir, Advice for?

### ISSUE THREAD

**Issue by fire** [parapluu/nifty#12]
Can you give any advice for how to generate nifty wrappings for elixir?

I am trying to wrap https://github.com/bkaradzic/bgfx/blob/master/include/bgfx/c99/bgfx.h My first approach is to use nifty to generate erlang bindings and then convert them to elixir ones.

**Comment by kostis** [comment]
Did you encounter any problems in using nifty with this library/header file?  If so, please report them and we will try to address them. Otherwise, we do not really see how this issue is related to nifty...

**Comment by TheGeorge** [comment]
There is currently no support for enum's. This means that no wrappings for functions using them will be generated.

**Comment by TheGeorge** [comment]
By the way, after #13 you should be able to use enums and functions using enums.
