### ISSUE TITLE
rebar dependency only used for dialyzer

### ISSUE THREAD

**Issue by sg2342** [parapluu/nifty#17]
Code from the rebar dependency in rebar.config (tracking HEAD since fc31d6d) is used by dialyzer but
when nifty:compile is run by the tests target, rebar_* modules from the supplied rebar (updated in 3afc2cb, reported version points to rebar/rebar@b0a8a11) will be used.

1. With the rebar dependency removed from rebar.config, the tests target succeeds (and the dialyze target reports missing rebar_* functions but succeeds anyways).

2. If code from the rebar HEAD dependency is used, nifty:compile fails with:
```
[sg@bath ~/devel/usb_sc/nifty]$ gmake  rebar_regression
erl -noshell -pa `pwd`/ebin -pa `pwd`/deps/*/ebin \
-eval 'erlang:halt(try nifty:compile("test/cfiles/types.h",foo,[]),0 catch _:_ -> io:format("~p~n",[erlang:get_stacktrace()]),1 end)'
[{ets,lookup,[rmemo,43361090],[]},
 {rmemo,call_1,1,[{file,"src/rmemo.erl"},{line,266}]},
 {rebar_utils,get_arch,0,[{file,"src/rebar_utils.erl"},{line,104}]},
 {rebar_port_compiler,default_env,0,
                      [{file,"src/rebar_port_compiler.erl"},{line,614}]},
 {rebar_port_compiler,setup_env,2,
                      [{file,"src/rebar_port_compiler.erl"},{line,182}]},
 {nifty_compiler,compile,3,[{file,"src/nifty_compiler.erl"},{line,192}]},
 {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},
 {erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,121}]}]
Makefile:56: recipe for target 'rebar_regression' failed
gmake: *** [rebar_regression] Error 1
```

I suggest to pin the rebar dependency to rebar/rebar@b0a8a11.

**Comment by TheGeorge** [comment]
I did not know that rebar would behave like this. For the time being I think we should do as you suggested.
