### ISSUE TITLE
nifty:dereference/1 is broken

### ISSUE THREAD

**Issue by sg2342** [parapluu/nifty#21]
`nifty:dereference(Pointer)` makes use of `get_derefed_type(Type,Module)` to find out if
`Type` of `Pointer` is `'final'` or `'pointer'`.

If both `"struct s *"` and `"struct s **"` are keys in the `dict` returned by `Module:get_types()`,
`get_derefed_type/1` will return `'final'` for `"struct s *"` (which is correct).

But it also returns `'final'` for  `"struct s **"` which leads to interesting behaviors if one tries to
use the result of the `nifty:derefrence/1` call.

A minimal testcase for this issue can be found at sg2342/nifty@44f66498ce8df9dfa3e0678bcfb08326b60856dc

The problem was discovered while trying to use nifty with libusb.

the code snippet taken from `get_derefed_type/2` in `nifty.erl`
```erlang
...
[_|Token] = lists:reverse(string:tokens(ResType, " ")),
NType = string:join(lists:reverse(Token), " "),
ResNType = nifty_types:resolve_type(NType, Types),
...
```
is most likely not doing what its author intended it to do.

**Comment by TheGeorge** [comment]
This is definitely a bug. I'll look into this.
