### ISSUE TITLE
Support for NIF threads in the roadmap?

### ISSUE THREAD

**Issue by brainstormi** [parapluu/nifty#23]
The question is regarding to ingrate support for deploying NIF threading model, like it was done for NIF dirty thread, to support parsing C libraries that implies running an infinite main loop and aren't thread safe, like SDL or OpenGL. Not sure if it make sense for nifty scope or this is quite project specific, anyway I would like to know your thoughts.

**Comment by TheGeorge** [comment]
There is support (although not tested thoroughly) for [dirty schedulers already in nifty.](http://parapluu.github.io/nifty//news/support-for-dirty-schedulers/)

Another way of using long-running c-functions is to use the [safe-execution mode of nifty.](http://parapluu.github.io/nifty/tutorial5/) If you execute a c-module like this, then it is run in a dedicated erlang node and does not disturb the schedulers of other nodes. 

What kind of functionality would you desire?

**Comment by brainstormi** [comment]
Some C libraries need single threaded access to the API, the same thread that originally "instanced" it; so probably dirty scheduler is not an option because you should pin that thread to a scheduler for the execution of following commands during the lifecycle of the app.  
The idea was creating a NIF thread to serialize communication against these backends, being more efficient than linked-in driver alternative and at the same time simpler to implement.
See the following example as base about what I talk about:
https://github.com/davisp/nif-examples/tree/master/apps/termsend_threaded
Probably something difficult to automate it without understanding of the context of the library that we're parsing in that moment. As example of these, could be OpenGL (already exists a linked-in driver in erlang wx lib) or most graphics libraries so far.
