### ISSUE TITLE
How to pass char * type to c function?

### ISSUE THREAD

**Issue by OpakAlex** [parapluu/nifty#49]
Hello.
I have issue, how to pass `char *word` to some function?
hundspell_lib:
```C
char **hunhandle(char *word){
	Hunhandle *dic;
	int list_size, i;

	char **slist;

	dic = Hunspell_create("./src_c/spelling/en_US.aff", "./src_c/spelling/en_US.dic");

	printf("%i\n", Hunspell_spell(dic, word));

	list_size = Hunspell_suggest(dic, &slist, word);

	for (i = 0; i < list_size; i++)
	{
		printf("%s\n", slist[i]);
	}

	Hunspell_destroy(dic);
	return slist;
}
```
```elixir
  hundspell_lib = get_lib(registry, :hundspell_lib)
 # hundspell_lib it's a C library
  suggestions = hundspell_lib.hunhandle("heello")
```

ok, i can pass string as:
```
  suggestion = hundspell_lib.hunhandle(:nifty.mem_write("heello"))
```
Then i have return value like:
`{140712305422752, 'hunspell_c.char **'}`

### How i can get from this like: 
  `["hello", "heel lo", "heel-lo", "heel", "hell']`

@kostis can you help me?

**Comment by OpakAlex** [comment]
guys i need your help :) Please look, @TheGeorge

**Comment by OpakAlex** [comment]
How to read value from memory point if i don't known length?

**Comment by TheGeorge** [comment]
You can use nifty's array functions. Look at the documentation for more information: http://parapluu.github.io/nifty/api-doc/nifty.html
