### ISSUE TITLE
llvm version

### ISSUE THREAD

**Issue by a29107a** [parapluu/nifty#65]
hello, what llvm version i need?

i had install clang and version is 3.2

after i clone nifty,i make ok!

but, how i add the nifty to my erl_lib?
for this i take some days,but i cant use nifty!

**Comment by kostis** [comment]
As you can see in the [travis script](https://github.com/parapluu/nifty/blob/master/.travis.yml) we are testing nifty with Clang/LLVM versions ranging from 3.5.2 to 3.9.0, which is pretty recent.  As far as we know, it works correctly with all of them. Glad to know nifty can be built also with 3.2, but if I were you, I would use an Clang version more recent than 3.2.

As to adding nifty to your ERL_LIB, I guess this is done the standard way (with a `setenv`, `export`, etc. command, depending on your Unix shell), but you may also want to set some other environment variables in your PATH.  Take a look at the [travis script](https://github.com/parapluu/nifty/blob/master/.travis.yml) for some inspiration.
